### ISSUE TITLE
Cannot load extensions when compiled with musl

### ISSUE THREAD

**Issue by phinjensen** [rusqlite/rusqlite#990] opened 2021-07-10 01:20 UTC
I'm not sure if this is really a bug or if I am missing something, but when I compile for musl and try to load an extension, I get the following error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("Dynamic loading not supported"))', src/main.rs:10:14
```

main.rs:

```rust
use rusqlite::{Connection, LoadExtensionGuard};
use std::path::Path;

fn main() {
    let mut conn = Connection::open_in_memory().unwrap();

    {
        let _guard = LoadExtensionGuard::new(&conn).unwrap();
        conn.load_extension(Path::new("/usr/lib/sqlite3/pcre.so"), None)
            .unwrap();
    }
}
```

And Cargo.toml, which does have loading extensions and bundled sqlite included:

```toml
[package]
name = "rusqlite_test"
version = "0.1.0"
authors = ["Phineas Jensen <phin@zayda.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version = "0.25.0", features = ["load_extension", "bundled"] }
```

Is this a bug with rusqlite or sqlite or musl, or simply an unsupported feature? Does anyone know of any workarounds for it?

**Comment by thomcc** [comment] 2021-07-10 02:21
Rust currently assumes if you're compiling to a musl target, you want a fully statically linked binary, e.g. where even libc (and the other parts of the C runtime) are statically linked into the executable.

Statically linked binaries can't use dlopen generally. The issue is that none of the symbols from `libc` are available (they won't be exported from your excutable — nothing will) for the library-being-loaded to link against.

This isn't a musl issue — in theory Rust could allow non-static builds with musl (it *does* have a implementation of dlopen and such), just with the an assumption Rust makes about the reason you might target musl. I don't believe there's a good workaround (short of a writing custom target which uses musl without implying an implicit `-Ctarget-feature=+crt-static`).

I don't see a issue tracking *precisely* this problem, but I have seen it discussed a few times on Zulip, so imagine it exists. If you're motivated, you can look through these: https://github.com/rust-lang/rust/issues?page=1&q=is%3Aissue+is%3Aopen+dynamic+musl, which probably contains it.

**Comment by thomcc** [comment] 2021-07-10 16:50
Going to close this, since there’s nothing we can do

**Closed by thomcc** 2021-07-10 16:50 UTC
